/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArcoForm: typeof import('./src/components/parts/ArcoForm.vue')['default']
    CreatePage: typeof import('./src/components/layout/CreatePage.vue')['default']
    CreatePageDialog: typeof import('./src/components/parts/CreatePageDialog.vue')['default']
    CustomForm: typeof import('./src/components/parts/CustomForm.vue')['default']
    Editable: typeof import('./src/components/parts/Editable.vue')['default']
    Footer: typeof import('./src/components/menu/Footer.vue')['default']
    GridStackLayout: typeof import('./src/components/layout/GridStackLayout.vue')['default']
    LayoutParts: typeof import('./src/components/parts/LayoutParts.vue')['default']
    Menubar: typeof import('./src/components/menu/Menubar.vue')['default']
    MyPage: typeof import('./src/components/page/MyPage.vue')['default']
    Page: typeof import('./src/components/page/Page.vue')['default']
    PageList: typeof import('./src/components/page/PageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleListParts: typeof import('./src/components/parts/SimpleListParts.vue')['default']
    Test: typeof import('./src/components/test/Test.vue')['default']
    Top: typeof import('./src/components/page/Top.vue')['default']
    UploadForm: typeof import('./src/components/parts/UploadForm.vue')['default']
  }
}
