/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArcoForm: typeof import('./src/components/parts/ArcoForm.vue')['default']
    CreatePageDialog: typeof import('./src/components/dialog/CreatePageDialog.vue')['default']
    CustomForm: typeof import('./src/components/parts/CustomForm.vue')['default']
    Editable: typeof import('./src/components/parts/Editable.vue')['default']
    FileUpload: typeof import('./src/components/formkit/FileUpload.vue')['default']
    Footer: typeof import('./src/components/menu/Footer.vue')['default']
    FormExample: typeof import('./src/components/formkit/FormExample.vue')['default']
    FormKitIcon: typeof import('./src/components/formkit/FormKitIcon.vue')['default']
    FormkitInput: typeof import('./src/components/formkit/FormkitInput.vue')['default']
    GridMenu: typeof import('./src/components/layout/lygs/GridMenu.vue')['default']
    GridStackCreate: typeof import('./src/components/layout/lygs/GridStackCreate.vue')['default']
    GridStackLayout: typeof import('./src/components/layout/lygs/GridStackLayout.vue')['default']
    GridStackMultiCreate: typeof import('./src/components/layout/lygs/GridStackMultiCreate.vue')['default']
    GridStackMultiLayout: typeof import('./src/components/layout/lygs/GridStackMultiLayout.vue')['default']
    GridStackPage: typeof import('./src/components/page/GridStackPage.vue')['default']
    GridStackPageList: typeof import('./src/components/page/GridStackPageList.vue')['default']
    LayoutPageList: typeof import('./src/components/page/LayoutPageList.vue')['default']
    LayoutParts: typeof import('./src/components/parts/LayoutParts.vue')['default']
    Menubar: typeof import('./src/components/menu/Menubar.vue')['default']
    MyPage: typeof import('./src/components/page/MyPage.vue')['default']
    PageInfoDialog: typeof import('./src/components/dialog/PageInfoDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaKit: typeof import('./src/components/formkit/SchemaKit.vue')['default']
    SimpleListParts: typeof import('./src/components/parts/SimpleListParts.vue')['default']
    Test: typeof import('./src/components/test/Test.vue')['default']
    Test1: typeof import('./src/components/formkit/Test1.vue')['default']
    Top: typeof import('./src/components/page/Top.vue')['default']
    UploadForm: typeof import('./src/components/parts/UploadForm.vue')['default']
  }
}
