/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArcoForm: typeof import('./src/components/samples/ArcoForm.vue')['default']
    ComponentATest: typeof import('./src/components/test/ComponentATest.vue')['default']
    ComponentB: typeof import('./src/components/test/ComponentB.vue')['default']
    ComponentTitle: typeof import('./src/components/layout/ComponentTitle.vue')['default']
    copy: typeof import('./src/components/layout/GridMenu copy.vue')['default']
    CreatePageDialog: typeof import('./src/components/dialog/CreatePageDialog.vue')['default']
    DefaultGsPage: typeof import('./src/components/page/DefaultGsPage.vue')['default']
    DefaultGsPageCreate: typeof import('./src/components/page/DefaultGsPageCreate.vue')['default']
    FileUpload: typeof import('./src/components/formkit/FileUpload.vue')['default']
    Footer: typeof import('./src/components/menu/Footer.vue')['default']
    FormExample: typeof import('./src/components/samples/FormExample.vue')['default']
    FormKitIcon: typeof import('./src/components/formkit/FormKitIcon.vue')['default']
    FormkitInput: typeof import('./src/components/formkit/FormkitInput.vue')['default']
    GridMenu: typeof import('./src/components/layout/GridMenu.vue')['default']
    GridStackCreate: typeof import('./src/components/layout/GridStackCreate.vue')['default']
    GridStackLayout: typeof import('./src/components/layout/GridStackLayout.vue')['default']
    GridStackNaviPanel: typeof import('./src/components/layout/GridStackNaviPanel.vue')['default']
    GridStackPage: typeof import('./src/components/layout/GridStackPage.vue')['default']
    GridStackPageList: typeof import('./src/components/page/GridStackPageList.vue')['default']
    Image: typeof import('./src/components/test/Image.vue')['default']
    Menubar: typeof import('./src/components/menu/Menubar.vue')['default']
    MyPage: typeof import('./src/components/page/MyPage.vue')['default']
    PageInfoDialog: typeof import('./src/components/dialog/PageInfoDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaForm: typeof import('./src/components/formkit/SchemaForm.vue')['default']
    SchemaKit: typeof import('./src/components/formkit/SchemaKit.vue')['default']
    SimpleListParts: typeof import('./src/components/parts/SimpleListParts.vue')['default']
    TestConfig: typeof import('./src/components/test/TestConfig.vue')['default']
    TestLoad: typeof import('./src/components/test/TestLoad.vue')['default']
    Top: typeof import('./src/components/page/Top.vue')['default']
  }
}
